name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Downloading...
      run: wget https://getcomposer.org/installer -o composer-install.php
      
    - name: Installing...
      run: |
        clear
        echo "-------------------------------"
        echo; echo 
        cat ./composer-install.php
        echo; echo "--------------------------------"; echo; echo
