name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Downloading...
      run: wget https://getcomposer.org/installer -O composer-install.php
      
    - name: Installing...
      run: cat ./composer-install.php
